lowestYNormalCustom: -60
highestYNormalCustom: 320
lowestYNether: 4
highestYNether: 120
lowestYEnd: 0
highestYEnd: 320
normalCustomAirBuildingMinAltitude: 80
normalCustomAirBuildingMaxAltitude: 120
endAirBuildMinAltitude: 80
endAirBuildMaxAltitude: 120
warnAdminsAboutNewBuildings: true
regionProtectedMessage: '&8[BetterStructures] &cDefeat the zone''s bosses to edit
  blocks!'
protectEliteMobsRegions: true
setupDone: false
modularChunkPastingSpeed: 10
# Sets the maximum percentage of a tick that BetterStructures will use to paste builds, however many it maybe trying to generate.
# Ranges from 0.01 to 1, where 0.01 is 1% and 1 is 100%.
# Slower speeds will lower performance impact, but can lead to other problems such as builds suddenly popping in.
percentageOfTickUsedForPasting: 0.2
distanceSurface: 31
distanceShallow: 22
distanceDeep: 22
distanceSky: 95
distanceLiquid: 65
maxOffsetSurface: 5
maxOffsetShallow: 5
maxOffsetDeep: 5
maxOffsetSky: 5
maxOffsetLiquid: 5
